version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
    volumes:
      - backend_data:/app/data
      - ./backend:/app
    user: "${UID:-1000}:${GID:-1000}"
    command: >
      bash -c "mkdir -p /app/data &&
               touch /app/data/db.sqlite3 &&
               chmod 666 /app/data/db.sqlite3 &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

volumes:
  backend_data:
