version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - PYTHONPATH=/app
    volumes:
      # Use delegated mode for better performance on macOS
      - ./backend:/app:delegated
      # Named volume for persistent data
      - django_data:/app/data:delegated
    command: >
      bash -c "
        # Ensure correct line endings
        find . -type f -name '*.py' -exec dos2unix {} + 2>/dev/null || true &&
        # Create directories if they don't exist
        mkdir -p /app/data /app/media /app/static &&
        # Set permissions
        chmod -R 777 /app/data /app/media /app/static &&
        # Run migrations
        python manage.py makemigrations &&
        python manage.py migrate &&
        # Start server
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  django_data:
    # Use local driver for better cross-platform support
    driver: local
