# Generated by Django 5.0 on 2024-12-21 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareableLink',
            fields=[
                ('token', models.CharField(editable=False, help_text='Unique, secure token for the shareable link', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('permissions', models.CharField(choices=[('view', 'View Only'), ('download', 'Download')], default='view', help_text='Access permissions (view-only or download)', max_length=10)),
                ('expires_at', models.DateTimeField(help_text='Expiration time of the token')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the link was created')),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='When the link was last accessed', null=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this link has been accessed')),
                ('accessed_by', models.ForeignKey(blank=True, help_text='User who last accessed the link (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessed_links', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created the link', on_delete=django.db.models.deletion.CASCADE, related_name='created_links', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(help_text='The file being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shareable_links', to='files.file')),
            ],
            options={
                'verbose_name': 'Shareable Link',
                'verbose_name_plural': 'Shareable Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
