# Generated by Django 5.0 on 2024-12-24 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_shareablelink_guest_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shareablelink',
            name='exclusive_sharing_method',
        ),
        migrations.AddConstraint(
            model_name='shareablelink',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('guest_user__isnull', True), ('guest_user__isnull', False), _connector='OR')), name='exclusive_sharing_method'),
        ),
    ]
